#!/bin/bash

unzip /challenge/pyinstaller.zip -d /challenge/
pip install /challenge/pyinstaller/PyInstaller
pyinstaller --onefile flagCheck.py
mv /challenge/dist/flagCheck /challenge/
rm -r dist/ build/ flagCheck.spec 


